openapi: 3.0.0
info:
  title: Personal Finance Manager API
  description: API untuk manajemen keuangan pribadi
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Server Produksi
  - url: http://localhost:8000/v1
    description: Server Pengembangan

paths:
  /interest-rate:
    get:
      summary: Mendapatkan suku bunga terkini
      description: Mengembalikan suku bunga terbaru untuk perhitungan tabungan
      responses:
        '200':
          description: Sukses mendapatkan suku bunga
          content:
            application/json:
              schema:
                type: object
                properties:
                  rate:
                    type: number
                    format: float
                    example: 3.5
                    description: Suku bunga dalam persen
        '500':
          description: Error server internal